[package]
name = "bloomfilter"
version = "0.1.0"
authors = ["Dylan <meeusdylan@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rust-crypto = "^0.2"
